default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: opentableau_development

test:
  <<: *default
  database: opentableau_test

# production:
#   <<: *default
#   database: opentableau_production
#   username: opentableau
#   password: <%= ENV["<PROJECT_NAME>_DATABASE_PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>